### ISSUE TITLE
Current status?

### ISSUE THREAD

**Issue by lynxlynxlynx** [folklabs/openlocal#1]
Hey,

what development stage is OpenLocal in? There's no info here nor on the drupal distro page. I'll be setting up a site with some similar features, so I'm naturally wondering if this would be a sensible choice for a base. Currently everything is screaming NO. I suggest you add a short readme with a bit of info.

**Comment by pmackay** [comment]
I dont think OpenLocal is in a mature enough state to recommend using it. We're building a site using it and then need to backport and build a more robust distro, but its work-in-progress currently.
