### ISSUE TITLE
Organisations have information posted to Google Maps

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#13]
Feature request:

Any organisation having their location as a pin in a) google maps and b) openstreet view?

If a user clicked on the pin could the summary details of the trader/organisation pop up along with their picture and opening times?

**Comment by pmackay** [comment]
@GilesGibson this is about getting the org info onto google maps and OSM? Its almost not really a "Drupal" mapping feature cos it wouldnt have anything to do with maps on a Drupal/OpenLocal site.

**Comment by pmackay** [comment]
@GilesGibson I think this is outside the scope of OL currently.
