### ISSUE TITLE
Mapping feature - mobile maps

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#14]
Any asset (service, event, place) could be seen on google maps or Openstreet map when viewed on a users mobile. Clicking on the pin would show the details for the asset (opening times, background etc). All this information would come from the web site and/or Ohana?

**Comment by pmackay** [comment]
@GilesGibson this one is the same. Do you mean a Google Map/OSM map **on the Drupal site**, or separately on those service websites, e.g. maps.google.co.uk?

**Comment by GilesGibson** [comment]
It is about both:

A user who happens to be in the area will see information on their google maps without knowing about the web site. 

On the web site the mapping functionality will be greatly enhanced from what it currently is.

**Comment by pmackay** [comment]
OK, it would help t be specific about each of those as they are very
different things.

**Comment by GilesGibson** [comment]
OK, wasn't sure of the technical stuff behind it all.

**Comment by pmackay** [comment]
I think to be honest, after our discussion on Friday, the display of services or places on Google Maps is best handled via some kind of business import. If not a business, maybe same process, its not obvious. Events are impossible unless its an integration.

Going to close as seems like its covered by #15.
