### ISSUE TITLE
Create a basic brand image for themes and landing pages

### ISSUE THREAD

**Issue by pmackay** [folklabs/openlocal#2]

**Comment by djwesto** [comment]
No description provided... Please could you expand on the exact scope of this? Are you wanting essentially the same thing as we've started on CML – i.e. a styleguide and set of design comps? Or are you just talking about a logo?

**Comment by pmackay** [comment]
Yep, initially just a logo image would be handy, to use on d.o. page, a theme image (so its distinct on the Appearance page), our website, etc.
