### ISSUE TITLE
Contact form to have better security and improved UX

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#22]
The contact form needs slightly better security - Captcha or similar. Been getting spam from the VAC site.

**Comment by pmackay** [comment]
@GilesGibson can you give some more info or suggested text on what the description should be? What are better UX needs?

**Comment by GilesGibson** [comment]
the VAC site is better for the UX, more friendly etc. If we could add a simple captcha then we can reduce the spam.

**Comment by pmackay** [comment]
Recaptcha to be configured in pre-launch.
