### ISSUE TITLE
key menu areas

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#25]
Tabs:
1. About us
2. News
3. "register your interest" - capture peoples details plus areas of interest.
4. contact management - mailchimp (allow subscription to mailing list without having a login)
5. Management of "members". 
6. Campaigns - the ability to have a petition, poll. A landing page could have "we, the undersigned want XXX to be in the park...". Need to offer a "create a login/member of mailing list" at the point of clicking on the "petition".
7. closed group option - committee etc. share docs, news, comment, forum (or a closed non-public area of the main forum section). New users can be invited by the admin. 
8. Heritage tab. Posts of details and pictures.

**Comment by pmackay** [comment]
Some of these are going to need breaking out into separate discussions.

**Comment by GilesGibson** [comment]
we will split them out
