### ISSUE TITLE
Useful links page

### ISSUE THREAD

**Issue by GilesGibson** [folklabs/openlocal#28]
One page that has links and contacts details of key local things - essential services, councillors etc. Edited and curated by site admin.

**Comment by pmackay** [comment]
Could you add a more complete list of types of content you're thinking of here?

**Comment by GilesGibson** [comment]
Keep it simple as possible.

One large page of text and hyperlinks to the relevant web site/email/twitter/facebook links. Ideally as a twitter symbol, facebook symbol that could be edited to give a direct link when clicked.
