### ISSUE TITLE
Replace Business type with Organisation

### ISSUE THREAD

**Issue by pmackay** [folklabs/openlocal#5]
@GilesGibson this means Organisation will have a `type` field that defines if its a business, charity, etc. Could be multi-select. Can you suggest what values you think would be useful? And is this a chance to resolve the terminology difference between Business and Service?

**Comment by GilesGibson** [comment]
Is this for every OL site?

a quick stab at this would give:
1. Business
2. charity
3. voluntary organisation.
4. service provider.
5. community group

**Comment by djwesto** [comment]
As a business owner myself, I'd struggle to decide what you mean by "Service provider".

By "Service provider", are you really meaning "Public service" like a GP surgery or a Citizen's Advice Bureau?

I'd want to see some examples of each of these to help me understand what they all mean...

**Comment by GilesGibson** [comment]
agreed. 

I suppose it is about what you sell, is it an object or a service? You may be both. Business implies a "for profit" organisation. Service provider may well be as well but a charity may also be a service provider and they may have a trading arm that is a for profit business - Oxfam for instance.

**Comment by pmackay** [comment]
Also would be good to clarify what would be used as the filter for the
Services page. Would it just be Business similar to current site? Or
Include more of these categories?

**Comment by djwesto** [comment]
It would help to come at this from a different angle, by gathering up all the types of orgs you want to feature in this section. Once we can look at them all we can start to divide them up into logical groups.

We already know you've got businesses of all sorts of types in there: personal trainers and coaches, healers, shops and retailers, (possibly even some manufacturers) etc. So businesses which provide a service are already catered for by the Business category. But my thought the other day was that you would probably also want to start gathering public services such as GPs, opticians, dentists, carers / child carers, etc. Would those be classified as "Public services"?

To @pmackay's question, I see why you're asking this – showing Businesses and Services under the "Services" menu option no longer makes any sense. So should we perhaps think about adding either more top level menu options to cover Businesses as a different listing to Services or should we change the name of the Services menu and offer a second level menu on that page to allow users to distinguish between Service-providers and Businesses?

**Comment by GilesGibson** [comment]
I think a top level menu page is essential. After that the user can filter what they think they want to see. I wouldn't initially want to go down the line of "Public services" and non-public services. Dentists are invariably both, for instance. The distinction is blurring over time.

**Comment by pmackay** [comment]
Sounds like we might need a skype to discuss...

**Comment by pmackay** [comment]
Questions we need to consider:
- What menu item(s)s are used? 
- If Services is still there, what does it show?
- If Groups use Organisation to capture their info, is that a problem? Would there be crossover with categories, tags?
- Is there any other page or listing for orgs needed that is not under Services page?

**Comment by djwesto** [comment]
### Following Skype chat on Tues 14 April 2015...
- Refer to 00 doc – last section is relevant to this issue.

We discussed that there are more types of orgs now, more than we originally built the site for, so...
- How do we filter out each type of org/service? How will users differentiate between them?
- We suggested we should set up the site to allow "Organisations" to also have a Drupal Organic Group attached to them – this would work well to allow some groups or orgs or businesses to allow "Members" to contribute content. @pmackay suggested we could simply offer a flag to allow orgs to activate the Organic Groups functionality.
- @GilesGibson gave the example that the HH Forum could become a trading body so it's not just a one way benefit – all groups could benefit from greater flexibility.
- We discussed the idea of having a taxonomy for community groups and a separate one for businesses
- Should we add a way to filter by tags on Groups / Orgs landing page? What about News? @GilesGibson seemed to think this would be useful for users but I'm not convinced – wouldn't a stronger search results page work better for this?

Meeting was adjourned at 17:30 to be continued.

**Comment by djwesto** [comment]
Did we answer Paul's earlier questions last night?

On Tuesday, 14 April 2015, Paul Mackay notifications@github.com wrote:

> Questions we need to consider:
> - What menu item(s)s are used?
> - If Services is still there, what does it show?
> - If Groups use Organisation to capture their info, is that a problem?
>   Would there be crossover with categories, tags?
> - Is there any other page or listing for orgs needed that is not under
>   Services page?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/folklabs/openlocal/issues/5#issuecomment-92797441.

## 

---

_Chris Wells_\* Co-founder & Creative Director*
Folk Labs Ltd           www.folklabs.com           linkedin
http://lnkd.in/uZxawZ          twitter @djwesto
http://www.twitter.com/djwesto          mobile +44 (0)7786 221 654

**Comment by pmackay** [comment]
Still not clear on everything.
- I assume the Services menu item is still fine.
- What values in `Organisation type` field would be used to filter what is on Services page? Could it just be anything that is **not** marked as a `community group`?
- Assume we **dont** have any other page showing Orgs for now, but that's easier to add later (changing content model and connections is harder).
- I might try to use a single category taxonomy, but remove faceted search **for now**. Vassall wont need it so urgently.
- Propose keeping Groups separate as they are for now, but see how time goes.

Need to keep current changes to a relatively small amount, otherwise we never finish.

**Comment by GilesGibson** [comment]
Are these proposed changes to OL?
Will they filter to HH at some stage?

If we are to standardise on categories across the site then we should not limit it at any time on the filters. A community group could provide a service or have a business side to them. 

I think only one page (for now) to show organisations is fine.

If we are to merge groups and services onto OG then can we in the short term add in social media and web site fields to groups?

**Comment by pmackay** [comment]
Yes changes to OL. Filter to HH will happen when an update can be done. I think bigger question now is how much is done before creating a Vassall site.

**Comment by pmackay** [comment]
I still would like to know if the Services page should just be maintained as it is? And represent all Organisations?

**Comment by GilesGibson** [comment]
Apologies, not quite sure of the implications of the question. Is this about merging services and groups into OG format but displaying them in different areas?

If it is then I do think we need to keep the display of each sort separate. What I would like to see is how it would work from the users perspective, all being stored as an OG.

**Comment by pmackay** [comment]
Putting OG aside for now, I just need to know if you want the Services page largely as it is now, but with more Orgs?

**Comment by GilesGibson** [comment]
sorry to be thick but I am not understanding this. Are you suggesting displaying the groups in the services page?

**Comment by djwesto** [comment]
Yes, can you provide a bit more detail or a summation of what you're proposing @pmackay ? I'm not with you either and I can't trace back over your previous posts to this GH issue to find out what you're talking about. Maybe start from the beginning again...?

**Comment by pmackay** [comment]
Put another way: if you view the Services page, what do you want to see?

**Comment by pmackay** [comment]
After deliberation and discussion with @GilesGibson, I'm thinking a simple control like the mockup below is a way forward for deciding how to place Organisations in either Community or Services section. This would be a hardcoded selection, not easily changed without code updates, but separate from the `Organisation type` field. Could you guys check and comment? 

![screen shot 2015-04-21 at 15 22 54](https://cloud.githubusercontent.com/assets/115115/7254382/ab953a4e-e83a-11e4-9a46-8bed44f6851f.png)

**Comment by djwesto** [comment]
Great stuff mate! I quite like this idea of posting wireframes into the issue queue. Good call.

A few comments on usability issues for this proposal:
- Annoying question: is it scalable to make this a hard-coded selection, rather than a taxonomic selection (what if we needed to draw a more granular distinction in future)?
- Is there any chance we could avoid this appearing on a separate tab all on its own? Would it be easier to change classification settings as part of Basic Info?
- What do you think about the wording @GilesGibson? I'm still not keen on your insistence to use "Service" to describe such a broad category of organisations. I think it sounds very council-focused and not what locals would call things like this...
- Any chance we could change "Organisation filter" to be a bit less techie too? If this field is really all about describing what sort of organisation this is, then let's make this label active:

> Is your organisation a:
> - [ ] **Community group** _such as park volunteers, book groups, sports teams, campaigners and residents associations_
> - [ ] **Service providers** _such as builders, personal trainers, shops, GP's surgeries, the police and cleaners, nannies and carers_

**Comment by pmackay** [comment]
> Annoying question: is it scalable to make this a hard-coded selection

Would prefer not but cannot think of any other way to define 2 filtered views in Community and Services. We cannot use taxonomy terms because they are "content" and its a bad idea to build a view (and save to features) that depends on a term value.

> Is there any chance we could avoid this appearing on a separate tab all on its own?

There are categories and tags on there too, just didnt draw them.

> Any chance we could change "Organisation filter" to be a bit less techie too?

Yes, as long as the label text fits in the "label" (not sure what limit is). Can add description underneath too if useful.

**Comment by djwesto** [comment]
Well, that seems pretty good to me then. Categories and tags makes sense on that tab. I'd be fine with leaving it there then.

Please let us know what sort of limit there is on that label text and I can re-write to fit.

**Comment by GilesGibson** [comment]
I am not wedded to the term "service provider". It is only there until a better description comes along that captures everything that is relevant.

I would prefer that the categorisation of the organisation happens right on the basic first page, that way people will see it. Put it on it's own tab and it will be forgotten/missed/ignored.

**Comment by pmackay** [comment]
@djwesto the only problem with a label saying "Is your organisation a?" is that it sounds very similar to Organisation type. The purpose of this filter field is just to select which part of the site the org goes into.

So we now have:

![screen shot 2015-04-23 at 10 35 32](https://cloud.githubusercontent.com/assets/115115/7294371/889bcdee-e9a4-11e4-9cbe-7f42b13f13fb.png)

**Comment by djwesto** [comment]
So, if the purpose of the filter field is to determine which part of the site the org will be visible in, why don't we just ask that? How does this sound?

#### Display this organisation in:
- [ ] Community groups section
- [ ] Service providers section

#### This organisation is a:
- [ ] Business
- [ ] Community group
- [ ] Association
- [ ] Charity
- [ ] Public service
- [ ] ...

**Comment by pmackay** [comment]
FYI, another impact of this is that breadcrumbs wont work when viewing a single Org. There is no logical breadcrumb if they can go in Services or Community.

**Comment by djwesto** [comment]
Can you give us examples of this problem? I can't quite understand it. At the moment, on HH, we see breadcrumbs for community groups which look like this:

> Home > Groups > Bilingual Primary Free School in SE London

And Service breadcrumbs resemble this:

> Home > Services > Brockwell Vetinery Surgery and Pet Store

So would this no longer work if all services and groups become "Organisations"?

**Comment by pmackay** [comment]
Actually breadcrumbs is partially solvable through using different layouts, which I've found are potentially possible. However there is no logical way to show a different layout depending on some state, that I can see. It is possible for the node author to select what panelizer layout is used (see below). Is this getting really messy or what? 

![screen shot 2015-04-23 at 13 26 29](https://cloud.githubusercontent.com/assets/115115/7297009/add026e2-e9bc-11e4-84e0-c3567313dde2.png)

**Comment by djwesto** [comment]
I assume this is no longer an issue if all Organisations are combined. Would the Directory section then feature breadcrumbs like this:

> Home > Directory > Bilingual Primary Free School in SE London

Or would we sub-divide them with their Type?

> Home > Directory > School > Bilingual Primary Free School in SE London
> 
> Home > Directory > Market stall > Bill's Fish Stall

**Comment by GilesGibson** [comment]
some traders would have market stall AND shop.

**Comment by djwesto** [comment]
Well, then, for simplicity's sakes we'd just use _Home > Directory > Name of org_ and leave it at that then.

**Comment by pmackay** [comment]
Here's a first cut of a directory page http://live-openlocaldev.pantheon.io/directory with a Community groups dropdown, and an org type facet filter.

As discussed, Orgs can have different page layouts using Panelizer (see image above) if they want to have a group or basic biz profile, etc.

**Comment by GilesGibson** [comment]
do we have the taxonomy for org types? This may work quite well I think as long as we can have a good category of org types and some orgs being in more than one type.

**Comment by pmackay** [comment]
Feel free to suggest the terms you'd like to use?

**Comment by GilesGibson** [comment]
Community group
Campaign
Local trader
service provider
market stall
Public service

Can we update the list and it then updates on the site?

**Comment by pmackay** [comment]
Yes its another taxonomy so any terms can be added/removed.

**Comment by GilesGibson** [comment]
great. All looking really good then.

And allowing groups/traders to change their layout? How is that being allowed/policed?

**Comment by pmackay** [comment]
Not created any extra layouts yet but its possible. What do you mean by
allowed? And how would you want it policed?

**Comment by GilesGibson** [comment]
Are we allowing traders or community orgs etc to move the layout around as they see fit or are we restricting it to a couple of layouts they can choose from? Bit worried that the style will go all over the place and annoy the style police @djwesto

**Comment by pmackay** [comment]
Just choose from 2-3 layouts I guess.

**Comment by GilesGibson** [comment]
OK, I think that would work. @djwesto - OK with you?

**Comment by djwesto** [comment]
Ideally I'd love to see the layout change only once a simple org chooses to become an active group. But I understand from @pmackay that you can't do that so if they (or perhaps a site admin) could go in and change their page layout after they've upgraded that would be a reasonably acceptable Plan B.

**Comment by djwesto** [comment]
I'd still like to at least _try_ to design a common layout that would work for both needs and would then remove the need for having two layouts in the first place.

**Comment by djwesto** [comment]
@pmackay, how can we figure out a list of all the panels which will appear in each of the "layouts"? If I can see a list then I could work out an optimised layout.

**Comment by pmackay** [comment]
Couldnt you just look at the list of panels in each of the current layouts?

**Comment by djwesto** [comment]
If it's safe to do that then that's exactly what I'll do. Just wanted to check nothing would be changing in that regard.

**Comment by pmackay** [comment]
Would it make sense for now to use the 2 page layouts we have?

**Comment by djwesto** [comment]
We could start out with the two existing layouts, but I'm expecting there to be a need to move things around slightly because of the way we're changing how the site works.

**Comment by pmackay** [comment]
Built on VAC. Closing for now.
